#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 21 14:50:50 2016

@author: Jack
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load Data
with pd.HDFStore('data/train.h5') as train:
    df = train.get('train')
    
df.head()