#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 21 17:11:38 2016

@author: Jack
"""
# Import dependencies
from numpy import random, array
%matplotlib inline
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
from numpy import random, float

## Import Data
with pd.HDFStore('/Users/Jack/Documents/gitTesting/data/train.h5') as train:
    df = train.get('train')

#Sampling for testing
sampleAssetIDs = df['id'].drop_duplicates().sample(frac=0.05)
df = df.loc[df['id'].isin(sampleAssetIDs)]

## Cleaning
# Exclude NAs
def fillColumnNAs(colName):
    df[colName] = df[colName].fillna(df[colName].median())
    df[colName] = df[colName].fillna(0)
    
for i in df.columns:
    fillColumnNAs(i)
    
## Learning algorthim
model = KMeans(n_clusters=10)
model = model.fit(scale(df))

df['unsupervisedGrouping'] = model.labels_

df.groupby(['unsupervisedGrouping'])['id'].nunique()